a mess of variables

diff --git a/ttable-train b/ttable-train
--- a/ttable-train
+++ b/ttable-train
@@ -1,11 +1,43 @@
 #!/bin/bash
 # prepare the phrase table from alignment and opus
 
-encs=$1
-echo $encs
+
+################ function ##############################
+function die() { echo "$@" | tee FAILED >&2; exit 1 ; }
+
+################ pass variables #####################
+
+SRC=$1
+TGT=$2
+ALI=$3
+# PIPE is the name of the alignment that we have
+# it is pivot-* such as: encs if we translate cs-en-uk or uk-en-cs
+PIPE="$1$2"
+
 SCRIPT_ROOTDIR=/a/merkur3/thoang/eman/ufal-smt-playground/multi_playground/s.mosesgiza.f282bc2e.20140906-1739/moses/scripts
+
 DIR=$(pwd)
 
+echo "creating the phrase table of $PIPE"
+
+############### create temporary dir ##################
+maintempdir=/mnt/h/tmp
+[ -d \$maintempdir ] || maintempdir=/tmp
+
+tempdir=\`mktemp -d \$maintempdir/exp.model.XXXXXX\`
+echo "COPYING corpus and alignment TO TEMPDIR: \$tempdir"
+
+# there is a difference in the file alignment.gz and the final alignment, there are two extra columns which I have no idea what is the benefit
+zcat $DIR/$PIPE/Opus.$PIPE.ali.gz | cut -f 1 | gzip -c > temp/$PIPE/alignment.custom.gz
+ln -sfn $DIR/$PIPE/Opus.en.tok.gz temp/PIPE/corpus.src.gz
+ln -sfn $DIR/$PIPE/Opus.cs.tok.gz temp/PIPE/corpus.tgt.gz
+
+echo "COPIED, used disk space:"
+
+df \$tempdir
+
+
+####################### run the script ########################
 # delete previous tm and temp
 rm -rf tm temp
 
@@ -15,11 +47,11 @@ mkdir tm/csuk
 
 # make symlink from directory to some random folder
 mkdir temp
-mkdir temp/encs
+mkdir temp/PIPE
 # there is a difference in the file alignment.gz and the final alignment, there are two extra columns which I have no idea what is the benefit
-zcat $DIR/$encs/Opus.encs.ali.gz | cut -f 1 | gzip -c > temp/encs/alignment.custom.gz
-ln -sfn $DIR/$encs/Opus.en.tok.gz temp/encs/corpus.src.gz
-ln -sfn $DIR/$encs/Opus.cs.tok.gz temp/encs/corpus.tgt.gz
+zcat $DIR/$PIPE/Opus.PIPE.ali.gz | cut -f 1 | gzip -c > temp/PIPE/alignment.custom.gz
+ln -sfn $DIR/$PIPE/Opus.en.tok.gz temp/PIPE/corpus.src.gz
+ln -sfn $DIR/$PIPE/Opus.cs.tok.gz temp/PIPE/corpus.tgt.gz
 
 mkdir tm/csuk/model
 
@@ -27,7 +59,7 @@ $SCRIPT_ROOTDIR/training/train-model.perl \
     --force-factored-filenames \
     --first-step 4 --last-step 6 \
     --root-dir tm/csuk \
-    --alignment-file=temp/encs/alignment \
+    --alignment-file=temp/PIPE/alignment \
     --alignment=custom \
-    --corpus=temp/encs/corpus \
+    --corpus=temp/PIPE/corpus \
     --f src --e tgt --translation-factors 0-0 --decoding-steps t0
